# Generated by Django 4.2.3 on 2023-07-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('cvr_url', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='price',
        ),
    ]
