# Generated by Django 4.2.3 on 2023-07-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_ebook_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisp',
            name='cvr_url',
        ),
    ]
