# Generated by Django 4.2.3 on 2023-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_crisp_cvr_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaffleUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
