# Generated by Django 4.2.4 on 2023-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
