# Generated by Django 4.2.3 on 2023-08-18 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_merchantdiscount_delete_crisp_delete_waffleup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantdiscount',
            name='product',
        ),
        migrations.AddField(
            model_name='merchantdiscount',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Store.ebook'),
        ),
    ]
