# Generated by Django 4.2.4 on 2023-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_orders_order_date_orders_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
