# Generated by Django 4.2.4 on 2023-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_alter_orders_order_date_alter_orders_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='storeID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
